[project]
name = "kraken-engine"
version = "1.7.5"
description = "A 2D game engine for Python and C++"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Derrick Martinez" }]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Programming Language :: C++",
  "Topic :: Games/Entertainment",
  "Topic :: Multimedia :: Graphics",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = ["nanobind-backend>=1.0"]

[project.urls]
"Homepage" = "https://krakenengine.org/"
"Issues" = "https://github.com/Kraken-Engine/PyKraken/issues"
"Documentation" = "https://krakenengine.org/docs"
"Release Notes" = "https://github.com/Kraken-Engine/PyKraken/releases"
"Source" = "https://github.com/Kraken-Engine/PyKraken"

[project.scripts]
kraken = "pykraken.cli:main"

[build-system]
requires = ["scikit-build-core >=1.0.0", "nanobind ==3.0.1"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"
wheel.py-api = "cp311"
wheel.packages = ["python/pykraken"]

[tool.cibuildwheel]
build-verbosity = 1

[tool.pytest]
minversion = "9.0"
testpaths = ["tests"]
addopts = ["-ra"]
strict_config = true
strict_markers = true
strict_parametrization_ids = true
strict_xfail = true
