#pragma once

#include <nanobind/nanobind.h>

namespace nb = nanobind;

#define KRAKEN_DECLARE_BINDING(name) \
    namespace kn::name               \
    {                                \
    void _bind(nb::module_& module); \
    }

KRAKEN_DECLARE_BINDING(animation_controller)
KRAKEN_DECLARE_BINDING(camera)
KRAKEN_DECLARE_BINDING(capsule)
KRAKEN_DECLARE_BINDING(circle)
KRAKEN_DECLARE_BINDING(collision)
KRAKEN_DECLARE_BINDING(color)
KRAKEN_DECLARE_BINDING(constants)
KRAKEN_DECLARE_BINDING(draw)
KRAKEN_DECLARE_BINDING(ease)
KRAKEN_DECLARE_BINDING(event)
KRAKEN_DECLARE_BINDING(font)
KRAKEN_DECLARE_BINDING(gamepad)
KRAKEN_DECLARE_BINDING(input)
KRAKEN_DECLARE_BINDING(key)
KRAKEN_DECLARE_BINDING(line)
KRAKEN_DECLARE_BINDING(log)
KRAKEN_DECLARE_BINDING(mask)
KRAKEN_DECLARE_BINDING(math)
KRAKEN_DECLARE_BINDING(mixer)
KRAKEN_DECLARE_BINDING(mouse)
KRAKEN_DECLARE_BINDING(orchestrator)
KRAKEN_DECLARE_BINDING(physics)
KRAKEN_DECLARE_BINDING(pixel_array)
KRAKEN_DECLARE_BINDING(polygon)
KRAKEN_DECLARE_BINDING(rect)
KRAKEN_DECLARE_BINDING(renderer)
KRAKEN_DECLARE_BINDING(shaders)
KRAKEN_DECLARE_BINDING(text)
KRAKEN_DECLARE_BINDING(texture)
KRAKEN_DECLARE_BINDING(tilemap)
KRAKEN_DECLARE_BINDING(time)
KRAKEN_DECLARE_BINDING(transform)
KRAKEN_DECLARE_BINDING(ui)
KRAKEN_DECLARE_BINDING(viewport)
KRAKEN_DECLARE_BINDING(window)

#undef KRAKEN_DECLARE_BINDING
