#pragma once

#include <SDL3/SDL.h>

namespace kn
{
enum class MouseButton : uint8_t
{
    Left = SDL_BUTTON_LEFT,
    Middle = SDL_BUTTON_MIDDLE,
    Right = SDL_BUTTON_RIGHT,
    Side1 = SDL_BUTTON_X1,
    Side2 = SDL_BUTTON_X2,
};

enum class Scancode
{
    A = SDL_SCANCODE_A,
    B = SDL_SCANCODE_B,
    C = SDL_SCANCODE_C,
    D = SDL_SCANCODE_D,
    E = SDL_SCANCODE_E,
    F = SDL_SCANCODE_F,
    G = SDL_SCANCODE_G,
    H = SDL_SCANCODE_H,
    I = SDL_SCANCODE_I,
    J = SDL_SCANCODE_J,
    K = SDL_SCANCODE_K,
    L = SDL_SCANCODE_L,
    M = SDL_SCANCODE_M,
    N = SDL_SCANCODE_N,
    O = SDL_SCANCODE_O,
    P = SDL_SCANCODE_P,
    Q = SDL_SCANCODE_Q,
    R = SDL_SCANCODE_R,
    S = SDL_SCANCODE_S,
    T = SDL_SCANCODE_T,
    U = SDL_SCANCODE_U,
    V = SDL_SCANCODE_V,
    W = SDL_SCANCODE_W,
    X = SDL_SCANCODE_X,
    Y = SDL_SCANCODE_Y,
    Z = SDL_SCANCODE_Z,

    Num1 = SDL_SCANCODE_1,
    Num2 = SDL_SCANCODE_2,
    Num3 = SDL_SCANCODE_3,
    Num4 = SDL_SCANCODE_4,
    Num5 = SDL_SCANCODE_5,
    Num6 = SDL_SCANCODE_6,
    Num7 = SDL_SCANCODE_7,
    Num8 = SDL_SCANCODE_8,
    Num9 = SDL_SCANCODE_9,
    Num0 = SDL_SCANCODE_0,

    Return = SDL_SCANCODE_RETURN,
    Escape = SDL_SCANCODE_ESCAPE,
    Backspace = SDL_SCANCODE_BACKSPACE,
    Tab = SDL_SCANCODE_TAB,
    Space = SDL_SCANCODE_SPACE,
    Minus = SDL_SCANCODE_MINUS,
    Equals = SDL_SCANCODE_EQUALS,
    LeftBracket = SDL_SCANCODE_LEFTBRACKET,
    RightBracket = SDL_SCANCODE_RIGHTBRACKET,
    Backslash = SDL_SCANCODE_BACKSLASH,
    Semicolon = SDL_SCANCODE_SEMICOLON,
    Apostrophe = SDL_SCANCODE_APOSTROPHE,
    Grave = SDL_SCANCODE_GRAVE,
    Comma = SDL_SCANCODE_COMMA,
    Period = SDL_SCANCODE_PERIOD,
    Slash = SDL_SCANCODE_SLASH,
    CapsLock = SDL_SCANCODE_CAPSLOCK,

    F1 = SDL_SCANCODE_F1,
    F2 = SDL_SCANCODE_F2,
    F3 = SDL_SCANCODE_F3,
    F4 = SDL_SCANCODE_F4,
    F5 = SDL_SCANCODE_F5,
    F6 = SDL_SCANCODE_F6,
    F7 = SDL_SCANCODE_F7,
    F8 = SDL_SCANCODE_F8,
    F9 = SDL_SCANCODE_F9,
    F10 = SDL_SCANCODE_F10,
    F11 = SDL_SCANCODE_F11,
    F12 = SDL_SCANCODE_F12,
    F13 = SDL_SCANCODE_F13,
    F14 = SDL_SCANCODE_F14,
    F15 = SDL_SCANCODE_F15,

    PrintScreen = SDL_SCANCODE_PRINTSCREEN,
    ScrollLock = SDL_SCANCODE_SCROLLLOCK,
    Pause = SDL_SCANCODE_PAUSE,
    Insert = SDL_SCANCODE_INSERT,
    Home = SDL_SCANCODE_HOME,
    PageUp = SDL_SCANCODE_PAGEUP,
    Delete = SDL_SCANCODE_DELETE,
    End = SDL_SCANCODE_END,
    PageDown = SDL_SCANCODE_PAGEDOWN,
    Right = SDL_SCANCODE_RIGHT,
    Left = SDL_SCANCODE_LEFT,
    Down = SDL_SCANCODE_DOWN,
    Up = SDL_SCANCODE_UP,

    NumLock = SDL_SCANCODE_NUMLOCKCLEAR,
    KpDivide = SDL_SCANCODE_KP_DIVIDE,
    KpMultiply = SDL_SCANCODE_KP_MULTIPLY,
    KpMinus = SDL_SCANCODE_KP_MINUS,
    KpPlus = SDL_SCANCODE_KP_PLUS,
    KpEnter = SDL_SCANCODE_KP_ENTER,
    Kp1 = SDL_SCANCODE_KP_1,
    Kp2 = SDL_SCANCODE_KP_2,
    Kp3 = SDL_SCANCODE_KP_3,
    Kp4 = SDL_SCANCODE_KP_4,
    Kp5 = SDL_SCANCODE_KP_5,
    Kp6 = SDL_SCANCODE_KP_6,
    Kp7 = SDL_SCANCODE_KP_7,
    Kp8 = SDL_SCANCODE_KP_8,
    Kp9 = SDL_SCANCODE_KP_9,
    Kp0 = SDL_SCANCODE_KP_0,
    KpPeriod = SDL_SCANCODE_KP_PERIOD,

    Application = SDL_SCANCODE_APPLICATION,
    Power = SDL_SCANCODE_POWER,
    Execute = SDL_SCANCODE_EXECUTE,
    Help = SDL_SCANCODE_HELP,
    Menu = SDL_SCANCODE_MENU,
    Select = SDL_SCANCODE_SELECT,
    Stop = SDL_SCANCODE_STOP,
    Again = SDL_SCANCODE_AGAIN,
    Undo = SDL_SCANCODE_UNDO,
    Cut = SDL_SCANCODE_CUT,
    Copy = SDL_SCANCODE_COPY,
    Paste = SDL_SCANCODE_PASTE,
    Find = SDL_SCANCODE_FIND,
    Mute = SDL_SCANCODE_MUTE,
    VolUp = SDL_SCANCODE_VOLUMEUP,
    VolDown = SDL_SCANCODE_VOLUMEDOWN,
    LeftCtrl = SDL_SCANCODE_LCTRL,
    LeftShift = SDL_SCANCODE_LSHIFT,
    LeftAlt = SDL_SCANCODE_LALT,
    LeftGui = SDL_SCANCODE_LGUI,
    RightCtrl = SDL_SCANCODE_RCTRL,
    RightShift = SDL_SCANCODE_RSHIFT,
    RightAlt = SDL_SCANCODE_RALT,
    RightGui = SDL_SCANCODE_RGUI,
    Mode = SDL_SCANCODE_MODE,
    Sleep = SDL_SCANCODE_SLEEP,
    Wake = SDL_SCANCODE_WAKE,
    ChannelInc = SDL_SCANCODE_CHANNEL_INCREMENT,
    ChannelDec = SDL_SCANCODE_CHANNEL_DECREMENT,
    MediaPlay = SDL_SCANCODE_MEDIA_PLAY,
    MediaPause = SDL_SCANCODE_MEDIA_PAUSE,
    MediaRec = SDL_SCANCODE_MEDIA_RECORD,
    MediaFastForward = SDL_SCANCODE_MEDIA_FAST_FORWARD,
    MediaRewind = SDL_SCANCODE_MEDIA_REWIND,
    MediaNext = SDL_SCANCODE_MEDIA_NEXT_TRACK,
    MediaPrev = SDL_SCANCODE_MEDIA_PREVIOUS_TRACK,
    MediaStop = SDL_SCANCODE_MEDIA_STOP,
    MediaEject = SDL_SCANCODE_MEDIA_EJECT,
    MediaPlayPause = SDL_SCANCODE_MEDIA_PLAY_PAUSE,
    MediaSelect = SDL_SCANCODE_MEDIA_SELECT,
    SoftLeft = SDL_SCANCODE_SOFTLEFT,
    SoftRight = SDL_SCANCODE_SOFTRIGHT,
    Call = SDL_SCANCODE_CALL,
    EndCall = SDL_SCANCODE_ENDCALL,
};

enum class GamepadButton
{
    South = SDL_GAMEPAD_BUTTON_SOUTH,
    East = SDL_GAMEPAD_BUTTON_EAST,
    West = SDL_GAMEPAD_BUTTON_WEST,
    North = SDL_GAMEPAD_BUTTON_NORTH,
    Back = SDL_GAMEPAD_BUTTON_BACK,
    Guide = SDL_GAMEPAD_BUTTON_GUIDE,
    Start = SDL_GAMEPAD_BUTTON_START,
    LeftStick = SDL_GAMEPAD_BUTTON_LEFT_STICK,
    RightStick = SDL_GAMEPAD_BUTTON_RIGHT_STICK,
    LeftShoulder = SDL_GAMEPAD_BUTTON_LEFT_SHOULDER,
    RightShoulder = SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER,
    DpadUp = SDL_GAMEPAD_BUTTON_DPAD_UP,
    DpadDown = SDL_GAMEPAD_BUTTON_DPAD_DOWN,
    DpadLeft = SDL_GAMEPAD_BUTTON_DPAD_LEFT,
    DpadRight = SDL_GAMEPAD_BUTTON_DPAD_RIGHT,
};

enum class GamepadAxis
{
    LeftX = SDL_GAMEPAD_AXIS_LEFTX,
    LeftY = SDL_GAMEPAD_AXIS_LEFTY,
    RightX = SDL_GAMEPAD_AXIS_RIGHTX,
    RightY = SDL_GAMEPAD_AXIS_RIGHTY,
    LeftTrigger = SDL_GAMEPAD_AXIS_LEFT_TRIGGER,
    RightTrigger = SDL_GAMEPAD_AXIS_RIGHT_TRIGGER,
};

enum class GamepadType
{
    Unknown = SDL_GAMEPAD_TYPE_UNKNOWN,
    Standard = SDL_GAMEPAD_TYPE_STANDARD,
    Xbox360 = SDL_GAMEPAD_TYPE_XBOX360,
    XboxOne = SDL_GAMEPAD_TYPE_XBOXONE,
    Ps3 = SDL_GAMEPAD_TYPE_PS3,
    Ps4 = SDL_GAMEPAD_TYPE_PS4,
    Ps5 = SDL_GAMEPAD_TYPE_PS5,
    SwitchPro = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO,
    SwitchJoyconLeft = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT,
    SwitchJoyconRight = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT,
    SwitchJoyconPair = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR,
    GameCube = SDL_GAMEPAD_TYPE_GAMECUBE,
};

enum class PenAxis
{
    Pressure = SDL_PEN_AXIS_PRESSURE,
    XTilt = SDL_PEN_AXIS_XTILT,
    YTilt = SDL_PEN_AXIS_YTILT,
    Distance = SDL_PEN_AXIS_DISTANCE,
    Rotation = SDL_PEN_AXIS_ROTATION,
    Slider = SDL_PEN_AXIS_SLIDER,
    TangentialPressure = SDL_PEN_AXIS_TANGENTIAL_PRESSURE,
};

class Vec2;
struct Anchor
{
    const static Vec2 TOP_LEFT;
    const static Vec2 TOP_MID;
    const static Vec2 TOP_RIGHT;
    const static Vec2 MID_LEFT;
    const static Vec2 CENTER;
    const static Vec2 MID_RIGHT;
    const static Vec2 BOTTOM_LEFT;
    const static Vec2 BOTTOM_MID;
    const static Vec2 BOTTOM_RIGHT;
};

enum class TextAlign
{
    Left,
    Center,
    Right,
};

enum class Keycode : SDL_Keycode
{
    Unknown = SDLK_UNKNOWN,
    Return = SDLK_RETURN,
    Esc = SDLK_ESCAPE,
    Backspace = SDLK_BACKSPACE,
    Tab = SDLK_TAB,
    Space = SDLK_SPACE,
    Exclaim = SDLK_EXCLAIM,
    DblQuote = SDLK_DBLAPOSTROPHE,
    Hash = SDLK_HASH,
    Dollar = SDLK_DOLLAR,
    Percent = SDLK_PERCENT,
    Ampersand = SDLK_AMPERSAND,
    SglQuote = SDLK_APOSTROPHE,
    LParen = SDLK_LEFTPAREN,
    RParen = SDLK_RIGHTPAREN,
    Asterisk = SDLK_ASTERISK,
    Plus = SDLK_PLUS,
    Comma = SDLK_COMMA,
    Minus = SDLK_MINUS,
    Period = SDLK_PERIOD,
    Slash = SDLK_SLASH,
    Num0 = SDLK_0,
    Num1 = SDLK_1,
    Num2 = SDLK_2,
    Num3 = SDLK_3,
    Num4 = SDLK_4,
    Num5 = SDLK_5,
    Num6 = SDLK_6,
    Num7 = SDLK_7,
    Num8 = SDLK_8,
    Num9 = SDLK_9,
    Colon = SDLK_COLON,
    Semicolon = SDLK_SEMICOLON,
    LessThan = SDLK_LESS,
    Equals = SDLK_EQUALS,
    GreaterThan = SDLK_GREATER,
    Question = SDLK_QUESTION,
    At = SDLK_AT,
    LeftBracket = SDLK_LEFTBRACKET,
    Backslash = SDLK_BACKSLASH,
    RightBracket = SDLK_RIGHTBRACKET,
    Caret = SDLK_CARET,
    Underscore = SDLK_UNDERSCORE,
    Grave = SDLK_GRAVE,
    A = SDLK_A,
    B = SDLK_B,
    C = SDLK_C,
    D = SDLK_D,
    E = SDLK_E,
    F = SDLK_F,
    G = SDLK_G,
    H = SDLK_H,
    I = SDLK_I,
    J = SDLK_J,
    K = SDLK_K,
    L = SDLK_L,
    M = SDLK_M,
    N = SDLK_N,
    O = SDLK_O,
    P = SDLK_P,
    Q = SDLK_Q,
    R = SDLK_R,
    S = SDLK_S,
    T = SDLK_T,
    U = SDLK_U,
    V = SDLK_V,
    W = SDLK_W,
    X = SDLK_X,
    Y = SDLK_Y,
    Z = SDLK_Z,
    LeftBrace = SDLK_LEFTBRACE,
    Pipe = SDLK_PIPE,
    RightBrace = SDLK_RIGHTBRACE,
    Tilde = SDLK_TILDE,
    Del = SDLK_DELETE,
    CapsLock = SDLK_CAPSLOCK,
    F1 = SDLK_F1,
    F2 = SDLK_F2,
    F3 = SDLK_F3,
    F4 = SDLK_F4,
    F5 = SDLK_F5,
    F6 = SDLK_F6,
    F7 = SDLK_F7,
    F8 = SDLK_F8,
    F9 = SDLK_F9,
    F10 = SDLK_F10,
    F11 = SDLK_F11,
    F12 = SDLK_F12,
    PrintScreen = SDLK_PRINTSCREEN,
    ScrollLock = SDLK_SCROLLLOCK,
    Pause = SDLK_PAUSE,
    Insert = SDLK_INSERT,
    Home = SDLK_HOME,
    PageUp = SDLK_PAGEUP,
    End = SDLK_END,
    PageDown = SDLK_PAGEDOWN,
    Right = SDLK_RIGHT,
    Left = SDLK_LEFT,
    Down = SDLK_DOWN,
    Up = SDLK_UP,
    NumLock = SDLK_NUMLOCKCLEAR,
    KpDivide = SDLK_KP_DIVIDE,
    KpMultiply = SDLK_KP_MULTIPLY,
    KpMinus = SDLK_KP_MINUS,
    KpPlus = SDLK_KP_PLUS,
    KpEnter = SDLK_KP_ENTER,
    Kp1 = SDLK_KP_1,
    Kp2 = SDLK_KP_2,
    Kp3 = SDLK_KP_3,
    Kp4 = SDLK_KP_4,
    Kp5 = SDLK_KP_5,
    Kp6 = SDLK_KP_6,
    Kp7 = SDLK_KP_7,
    Kp8 = SDLK_KP_8,
    Kp9 = SDLK_KP_9,
    Kp0 = SDLK_KP_0,
    KpPeriod = SDLK_KP_PERIOD,
    Application = SDLK_APPLICATION,
    Power = SDLK_POWER,
    F13 = SDLK_F13,
    F14 = SDLK_F14,
    F15 = SDLK_F15,
    Execute = SDLK_EXECUTE,
    Help = SDLK_HELP,
    Menu = SDLK_MENU,
    Select = SDLK_SELECT,
    Stop = SDLK_STOP,
    Again = SDLK_AGAIN,
    Undo = SDLK_UNDO,
    Cut = SDLK_CUT,
    Copy = SDLK_COPY,
    Paste = SDLK_PASTE,
    Find = SDLK_FIND,
    Mute = SDLK_MUTE,
    VolUp = SDLK_VOLUMEUP,
    VolDown = SDLK_VOLUMEDOWN,
    LeftCtrl = SDLK_LCTRL,
    LeftShift = SDLK_LSHIFT,
    LeftAlt = SDLK_LALT,
    LeftGui = SDLK_LGUI,
    RightCtrl = SDLK_RCTRL,
    RightShift = SDLK_RSHIFT,
    RightAlt = SDLK_RALT,
    RightGui = SDLK_RGUI,
    Mode = SDLK_MODE,
    Sleep = SDLK_SLEEP,
    Wake = SDLK_WAKE,
    ChannelInc = SDLK_CHANNEL_INCREMENT,
    ChannelDec = SDLK_CHANNEL_DECREMENT,
    MediaPlay = SDLK_MEDIA_PLAY,
    MediaPause = SDLK_MEDIA_PAUSE,
    MediaRec = SDLK_MEDIA_RECORD,
    MediaFastForward = SDLK_MEDIA_FAST_FORWARD,
    MediaRewind = SDLK_MEDIA_REWIND,
    MediaNext = SDLK_MEDIA_NEXT_TRACK,
    MediaPrev = SDLK_MEDIA_PREVIOUS_TRACK,
    MediaStop = SDLK_MEDIA_STOP,
    MediaEject = SDLK_MEDIA_EJECT,
    MediaPlayPause = SDLK_MEDIA_PLAY_PAUSE,
    MediaSelect = SDLK_MEDIA_SELECT,
    SoftLeft = SDLK_SOFTLEFT,
    SoftRight = SDLK_SOFTRIGHT,
    Call = SDLK_CALL,
    EndCall = SDLK_ENDCALL,
};
}  // namespace kn
