#pragma once

// Stable include for engine version info.
// The real values are generated by CMake into pykraken_version_generated.hpp.

#if defined(__has_include)
  #if __has_include("pykraken_version_generated.hpp")
    #include "pykraken_version_generated.hpp"
  #else
    #define KRAKEN_VERSION_STRING "0.0.0"
    #define KRAKEN_MAJOR_VERSION 0
    #define KRAKEN_MINOR_VERSION 0
    #define KRAKEN_MICRO_VERSION 0
  #endif
#else
  #define KRAKEN_VERSION_STRING "0.0.0"
  #define KRAKEN_MAJOR_VERSION 0
  #define KRAKEN_MINOR_VERSION 0
  #define KRAKEN_MICRO_VERSION 0
#endif
