#include "Constants.hpp"

#include <SDL3/SDL.h>
#include <pybind11/native_enum.h>

#include "_globals.hpp"

namespace kn::constants
{
void _bind(const py::module_& module)
{
    // Define Anchor enum
    py::native_enum<Anchor>(module, "Anchor", "enum.IntEnum")
        .value("TOP_LEFT", Anchor::TopLeft)
        .value("TOP_MID", Anchor::TopMid)
        .value("TOP_RIGHT", Anchor::TopRight)
        .value("MID_LEFT", Anchor::MidLeft)
        .value("CENTER", Anchor::Center)
        .value("MID_RIGHT", Anchor::MidRight)
        .value("BOTTOM_LEFT", Anchor::BottomLeft)
        .value("BOTTOM_MID", Anchor::BottomMid)
        .value("BOTTOM_RIGHT", Anchor::BottomRight)
        .finalize();

    // Define Align enum
    py::native_enum<Align>(module, "Align", "enum.IntEnum")
        .value("LEFT", Align::Left)
        .value("CENTER", Align::Center)
        .value("RIGHT", Align::Right)
        .finalize();

    // Define event types
    py::native_enum<SDL_EventType>(module, "EventType", "enum.IntEnum")
        .value("QUIT", SDL_EVENT_QUIT)
        .value("TERMINATING", SDL_EVENT_TERMINATING)
        .value("LOW_MEMORY", SDL_EVENT_LOW_MEMORY)
        .value("WILL_ENTER_BACKGROUND", SDL_EVENT_WILL_ENTER_BACKGROUND)
        .value("DID_ENTER_BACKGROUND", SDL_EVENT_DID_ENTER_BACKGROUND)
        .value("WILL_ENTER_FOREGROUND", SDL_EVENT_WILL_ENTER_FOREGROUND)
        .value("DID_ENTER_FOREGROUND", SDL_EVENT_DID_ENTER_FOREGROUND)
        .value("LOCALE_CHANGED", SDL_EVENT_LOCALE_CHANGED)
        .value("SYSTEM_THEME_CHANGED", SDL_EVENT_SYSTEM_THEME_CHANGED)

        // Display events
        .value("DISPLAY_ORIENTATION", SDL_EVENT_DISPLAY_ORIENTATION)
        .value("DISPLAY_ADDED", SDL_EVENT_DISPLAY_ADDED)
        .value("DISPLAY_REMOVED", SDL_EVENT_DISPLAY_REMOVED)
        .value("DISPLAY_MOVED", SDL_EVENT_DISPLAY_MOVED)
        .value("DISPLAY_DESKTOP_MODE_CHANGED", SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED)
        .value("DISPLAY_CURRENT_MODE_CHANGED", SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED)
        .value("DISPLAY_CONTENT_SCALE_CHANGED", SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED)
        .value("DISPLAY_USABLE_BOUNDS_CHANGED", SDL_EVENT_DISPLAY_USABLE_BOUNDS_CHANGED)

        // Window events
        .value("WINDOW_SHOWN", SDL_EVENT_WINDOW_SHOWN)
        .value("WINDOW_HIDDEN", SDL_EVENT_WINDOW_HIDDEN)
        .value("WINDOW_EXPOSED", SDL_EVENT_WINDOW_EXPOSED)
        .value("WINDOW_MOVED", SDL_EVENT_WINDOW_MOVED)
        .value("WINDOW_RESIZED", SDL_EVENT_WINDOW_RESIZED)
        .value("WINDOW_MINIMIZED", SDL_EVENT_WINDOW_MINIMIZED)
        .value("WINDOW_MAXIMIZED", SDL_EVENT_WINDOW_MAXIMIZED)
        .value("WINDOW_RESTORED", SDL_EVENT_WINDOW_RESTORED)
        .value("WINDOW_MOUSE_ENTER", SDL_EVENT_WINDOW_MOUSE_ENTER)
        .value("WINDOW_MOUSE_LEAVE", SDL_EVENT_WINDOW_MOUSE_LEAVE)
        .value("WINDOW_FOCUS_GAINED", SDL_EVENT_WINDOW_FOCUS_GAINED)
        .value("WINDOW_FOCUS_LOST", SDL_EVENT_WINDOW_FOCUS_LOST)
        .value("WINDOW_CLOSE_REQUESTED", SDL_EVENT_WINDOW_CLOSE_REQUESTED)
        .value("WINDOW_HIT_TEST", SDL_EVENT_WINDOW_HIT_TEST)
        .value("WINDOW_ICCPROF_CHANGED", SDL_EVENT_WINDOW_ICCPROF_CHANGED)
        .value("WINDOW_DISPLAY_CHANGED", SDL_EVENT_WINDOW_DISPLAY_CHANGED)
        .value("WINDOW_DISPLAY_SCALE_CHANGED", SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED)
        .value("WINDOW_SAFE_AREA_CHANGED", SDL_EVENT_WINDOW_SAFE_AREA_CHANGED)
        .value("WINDOW_OCCLUDED", SDL_EVENT_WINDOW_OCCLUDED)
        .value("WINDOW_ENTER_FULLSCREEN", SDL_EVENT_WINDOW_ENTER_FULLSCREEN)
        .value("WINDOW_LEAVE_FULLSCREEN", SDL_EVENT_WINDOW_LEAVE_FULLSCREEN)
        .value("WINDOW_DESTROYED", SDL_EVENT_WINDOW_DESTROYED)
        .value("WINDOW_HDR_STATE_CHANGED", SDL_EVENT_WINDOW_HDR_STATE_CHANGED)

        // Keyboard events
        .value("KEY_DOWN", SDL_EVENT_KEY_DOWN)
        .value("KEY_UP", SDL_EVENT_KEY_UP)
        .value("TEXT_EDITING", SDL_EVENT_TEXT_EDITING)
        .value("TEXT_INPUT", SDL_EVENT_TEXT_INPUT)
        .value("KEYMAP_CHANGED", SDL_EVENT_KEYMAP_CHANGED)
        .value("KEYBOARD_ADDED", SDL_EVENT_KEYBOARD_ADDED)
        .value("KEYBOARD_REMOVED", SDL_EVENT_KEYBOARD_REMOVED)
        .value("TEXT_EDITING_CANDIDATES", SDL_EVENT_TEXT_EDITING_CANDIDATES)
        .value("SCREEN_KEYBOARD_SHOWN", SDL_EVENT_SCREEN_KEYBOARD_SHOWN)
        .value("SCREEN_KEYBOARD_HIDDEN", SDL_EVENT_SCREEN_KEYBOARD_HIDDEN)

        // Mouse events
        .value("MOUSE_MOTION", SDL_EVENT_MOUSE_MOTION)
        .value("MOUSE_BUTTON_DOWN", SDL_EVENT_MOUSE_BUTTON_DOWN)
        .value("MOUSE_BUTTON_UP", SDL_EVENT_MOUSE_BUTTON_UP)
        .value("MOUSE_WHEEL", SDL_EVENT_MOUSE_WHEEL)
        .value("MOUSE_ADDED", SDL_EVENT_MOUSE_ADDED)
        .value("MOUSE_REMOVED", SDL_EVENT_MOUSE_REMOVED)

        // Gamepad events
        .value("GAMEPAD_AXIS_MOTION", SDL_EVENT_GAMEPAD_AXIS_MOTION)
        .value("GAMEPAD_BUTTON_DOWN", SDL_EVENT_GAMEPAD_BUTTON_DOWN)
        .value("GAMEPAD_BUTTON_UP", SDL_EVENT_GAMEPAD_BUTTON_UP)
        .value("GAMEPAD_ADDED", SDL_EVENT_GAMEPAD_ADDED)
        .value("GAMEPAD_REMOVED", SDL_EVENT_GAMEPAD_REMOVED)
        .value("GAMEPAD_REMAPPED", SDL_EVENT_GAMEPAD_REMAPPED)
        .value("GAMEPAD_TOUCHPAD_DOWN", SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN)
        .value("GAMEPAD_TOUCHPAD_MOTION", SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION)
        .value("GAMEPAD_TOUCHPAD_UP", SDL_EVENT_GAMEPAD_TOUCHPAD_UP)
        .value("GAMEPAD_SENSOR_UPDATE", SDL_EVENT_GAMEPAD_SENSOR_UPDATE)
        .value("GAMEPAD_UPDATE_COMPLETE", SDL_EVENT_GAMEPAD_UPDATE_COMPLETE)
        .value("GAMEPAD_STEAM_HANDLE_UPDATED", SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED)

        // Touch events
        .value("FINGER_DOWN", SDL_EVENT_FINGER_DOWN)
        .value("FINGER_UP", SDL_EVENT_FINGER_UP)
        .value("FINGER_MOTION", SDL_EVENT_FINGER_MOTION)
        .value("FINGER_CANCELED", SDL_EVENT_FINGER_CANCELED)

        // Drag and drop events
        .value("CLIPBOARD_UPDATE", SDL_EVENT_CLIPBOARD_UPDATE)
        .value("DROP_FILE", SDL_EVENT_DROP_FILE)
        .value("DROP_TEXT", SDL_EVENT_DROP_TEXT)
        .value("DROP_BEGIN", SDL_EVENT_DROP_BEGIN)
        .value("DROP_COMPLETE", SDL_EVENT_DROP_COMPLETE)
        .value("DROP_POSITION", SDL_EVENT_DROP_POSITION)

        // Audio device events
        .value("AUDIO_DEVICE_ADDED", SDL_EVENT_AUDIO_DEVICE_ADDED)
        .value("AUDIO_DEVICE_REMOVED", SDL_EVENT_AUDIO_DEVICE_REMOVED)
        .value("AUDIO_DEVICE_FORMAT_CHANGED", SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED)

        // Sensor events
        .value("SENSOR_UPDATE", SDL_EVENT_SENSOR_UPDATE)

        // Pen events
        .value("PEN_PROXIMITY_IN", SDL_EVENT_PEN_PROXIMITY_IN)
        .value("PEN_PROXIMITY_OUT", SDL_EVENT_PEN_PROXIMITY_OUT)
        .value("PEN_DOWN", SDL_EVENT_PEN_DOWN)
        .value("PEN_UP", SDL_EVENT_PEN_UP)
        .value("PEN_BUTTON_DOWN", SDL_EVENT_PEN_BUTTON_DOWN)
        .value("PEN_BUTTON_UP", SDL_EVENT_PEN_BUTTON_UP)
        .value("PEN_MOTION", SDL_EVENT_PEN_MOTION)
        .value("PEN_AXIS", SDL_EVENT_PEN_AXIS)

        // Camera events
        .value("CAMERA_DEVICE_ADDED", SDL_EVENT_CAMERA_DEVICE_ADDED)
        .value("CAMERA_DEVICE_REMOVED", SDL_EVENT_CAMERA_DEVICE_REMOVED)
        .value("CAMERA_DEVICE_APPROVED", SDL_EVENT_CAMERA_DEVICE_APPROVED)
        .value("CAMERA_DEVICE_DENIED", SDL_EVENT_CAMERA_DEVICE_DENIED)

        // Render events
        .value("RENDER_TARGETS_RESET", SDL_EVENT_RENDER_TARGETS_RESET)
        .value("RENDER_DEVICE_RESET", SDL_EVENT_RENDER_DEVICE_RESET)
        .value("RENDER_DEVICE_LOST", SDL_EVENT_RENDER_DEVICE_LOST)

        // Pinch gesture events
        .value("PINCH_BEGIN", SDL_EVENT_PINCH_BEGIN)
        .value("PINCH_UPDATE", SDL_EVENT_PINCH_UPDATE)
        .value("PINCH_END", SDL_EVENT_PINCH_END)

        .export_values()
        .finalize();

    // Mouse buttons
    py::native_enum<MouseButton>(module, "MouseButton", "enum.IntEnum")
        .value("M_LEFT", MouseButton::Left)
        .value("M_MIDDLE", MouseButton::Middle)
        .value("M_RIGHT", MouseButton::Right)
        .value("M_SIDE1", MouseButton::Side1)
        .value("M_SIDE2", MouseButton::Side2)
        .export_values()
        .finalize();

    // Pen Axis
    py::native_enum<SDL_PenAxis>(module, "PenAxis", "enum.IntEnum")
        .value("P_PRESSURE", SDL_PEN_AXIS_PRESSURE)
        .value("P_TILT_X", SDL_PEN_AXIS_XTILT)
        .value("P_TILT_Y", SDL_PEN_AXIS_YTILT)
        .value("P_DISTANCE", SDL_PEN_AXIS_DISTANCE)
        .value("P_ROTATION", SDL_PEN_AXIS_ROTATION)
        .value("P_SLIDER", SDL_PEN_AXIS_SLIDER)
        .value("P_TANGENTIAL_PRESSURE", SDL_PEN_AXIS_TANGENTIAL_PRESSURE)
        .export_values()
        .finalize();

    // Scancodes
    py::native_enum<SDL_Scancode>(module, "Scancode", "enum.IntEnum")
        .value("S_a", SDL_SCANCODE_A)
        .value("S_b", SDL_SCANCODE_B)
        .value("S_c", SDL_SCANCODE_C)
        .value("S_d", SDL_SCANCODE_D)
        .value("S_e", SDL_SCANCODE_E)
        .value("S_f", SDL_SCANCODE_F)
        .value("S_g", SDL_SCANCODE_G)
        .value("S_h", SDL_SCANCODE_H)
        .value("S_i", SDL_SCANCODE_I)
        .value("S_j", SDL_SCANCODE_J)
        .value("S_k", SDL_SCANCODE_K)
        .value("S_l", SDL_SCANCODE_L)
        .value("S_m", SDL_SCANCODE_M)
        .value("S_n", SDL_SCANCODE_N)
        .value("S_o", SDL_SCANCODE_O)
        .value("S_p", SDL_SCANCODE_P)
        .value("S_q", SDL_SCANCODE_Q)
        .value("S_r", SDL_SCANCODE_R)
        .value("S_s", SDL_SCANCODE_S)
        .value("S_t", SDL_SCANCODE_T)
        .value("S_u", SDL_SCANCODE_U)
        .value("S_v", SDL_SCANCODE_V)
        .value("S_w", SDL_SCANCODE_W)
        .value("S_x", SDL_SCANCODE_X)
        .value("S_y", SDL_SCANCODE_Y)
        .value("S_z", SDL_SCANCODE_Z)

        .value("S_1", SDL_SCANCODE_1)
        .value("S_2", SDL_SCANCODE_2)
        .value("S_3", SDL_SCANCODE_3)
        .value("S_4", SDL_SCANCODE_4)
        .value("S_5", SDL_SCANCODE_5)
        .value("S_6", SDL_SCANCODE_6)
        .value("S_7", SDL_SCANCODE_7)
        .value("S_8", SDL_SCANCODE_8)
        .value("S_9", SDL_SCANCODE_9)
        .value("S_0", SDL_SCANCODE_0)

        .value("S_RETURN", SDL_SCANCODE_RETURN)
        .value("S_ESC", SDL_SCANCODE_ESCAPE)
        .value("S_BACKSPACE", SDL_SCANCODE_BACKSPACE)
        .value("S_TAB", SDL_SCANCODE_TAB)
        .value("S_SPACE", SDL_SCANCODE_SPACE)
        .value("S_MINUS", SDL_SCANCODE_MINUS)
        .value("S_EQ", SDL_SCANCODE_EQUALS)
        .value("S_LBRACKET", SDL_SCANCODE_LEFTBRACKET)
        .value("S_RBRACKET", SDL_SCANCODE_RIGHTBRACKET)
        .value("S_BACKSLASH", SDL_SCANCODE_BACKSLASH)
        .value("S_SEMICOLON", SDL_SCANCODE_SEMICOLON)
        .value("S_APOSTROPHE", SDL_SCANCODE_APOSTROPHE)
        .value("S_GRAVE", SDL_SCANCODE_GRAVE)
        .value("S_COMMA", SDL_SCANCODE_COMMA)
        .value("S_PERIOD", SDL_SCANCODE_PERIOD)
        .value("S_SLASH", SDL_SCANCODE_SLASH)
        .value("S_CAPS", SDL_SCANCODE_CAPSLOCK)

        .value("S_F1", SDL_SCANCODE_F1)
        .value("S_F2", SDL_SCANCODE_F2)
        .value("S_F3", SDL_SCANCODE_F3)
        .value("S_F4", SDL_SCANCODE_F4)
        .value("S_F5", SDL_SCANCODE_F5)
        .value("S_F6", SDL_SCANCODE_F6)
        .value("S_F7", SDL_SCANCODE_F7)
        .value("S_F8", SDL_SCANCODE_F8)
        .value("S_F9", SDL_SCANCODE_F9)
        .value("S_F10", SDL_SCANCODE_F10)
        .value("S_F11", SDL_SCANCODE_F11)
        .value("S_F12", SDL_SCANCODE_F12)
        .value("S_F13", SDL_SCANCODE_F13)
        .value("S_F14", SDL_SCANCODE_F14)
        .value("S_F15", SDL_SCANCODE_F15)

        .value("S_PRTSCR", SDL_SCANCODE_PRINTSCREEN)
        .value("S_SCRLK", SDL_SCANCODE_SCROLLLOCK)
        .value("S_PAUSE", SDL_SCANCODE_PAUSE)
        .value("S_INS", SDL_SCANCODE_INSERT)
        .value("S_HOME", SDL_SCANCODE_HOME)
        .value("S_PGUP", SDL_SCANCODE_PAGEUP)
        .value("S_DEL", SDL_SCANCODE_DELETE)
        .value("S_END", SDL_SCANCODE_END)
        .value("S_PGDOWN", SDL_SCANCODE_PAGEDOWN)
        .value("S_RIGHT", SDL_SCANCODE_RIGHT)
        .value("S_LEFT", SDL_SCANCODE_LEFT)
        .value("S_DOWN", SDL_SCANCODE_DOWN)
        .value("S_UP", SDL_SCANCODE_UP)

        .value("S_NUMLOCK", SDL_SCANCODE_NUMLOCKCLEAR)
        .value("S_KP_DIV", SDL_SCANCODE_KP_DIVIDE)
        .value("S_KP_MULT", SDL_SCANCODE_KP_MULTIPLY)
        .value("S_KP_MINUS", SDL_SCANCODE_KP_MINUS)
        .value("S_KP_PLUS", SDL_SCANCODE_KP_PLUS)
        .value("S_KP_ENTER", SDL_SCANCODE_KP_ENTER)
        .value("S_KP_1", SDL_SCANCODE_KP_1)
        .value("S_KP_2", SDL_SCANCODE_KP_2)
        .value("S_KP_3", SDL_SCANCODE_KP_3)
        .value("S_KP_4", SDL_SCANCODE_KP_4)
        .value("S_KP_5", SDL_SCANCODE_KP_5)
        .value("S_KP_6", SDL_SCANCODE_KP_6)
        .value("S_KP_7", SDL_SCANCODE_KP_7)
        .value("S_KP_8", SDL_SCANCODE_KP_8)
        .value("S_KP_9", SDL_SCANCODE_KP_9)
        .value("S_KP_0", SDL_SCANCODE_KP_0)
        .value("S_KP_PERIOD", SDL_SCANCODE_KP_PERIOD)

        .value("S_APPLICATION", SDL_SCANCODE_APPLICATION)
        .value("S_POWER", SDL_SCANCODE_POWER)
        .value("S_EXECUTE", SDL_SCANCODE_EXECUTE)
        .value("S_HELP", SDL_SCANCODE_HELP)
        .value("S_MENU", SDL_SCANCODE_MENU)
        .value("S_SELECT", SDL_SCANCODE_SELECT)
        .value("S_STOP", SDL_SCANCODE_STOP)
        .value("S_AGAIN", SDL_SCANCODE_AGAIN)
        .value("S_UNDO", SDL_SCANCODE_UNDO)
        .value("S_CUT", SDL_SCANCODE_CUT)
        .value("S_COPY", SDL_SCANCODE_COPY)
        .value("S_PASTE", SDL_SCANCODE_PASTE)
        .value("S_FIND", SDL_SCANCODE_FIND)
        .value("S_MUTE", SDL_SCANCODE_MUTE)
        .value("S_VOLUP", SDL_SCANCODE_VOLUMEUP)
        .value("S_VOLDOWN", SDL_SCANCODE_VOLUMEDOWN)

        .value("S_LCTRL", SDL_SCANCODE_LCTRL)
        .value("S_LSHIFT", SDL_SCANCODE_LSHIFT)
        .value("S_LALT", SDL_SCANCODE_LALT)
        .value("S_LGUI", SDL_SCANCODE_LGUI)
        .value("S_RCTRL", SDL_SCANCODE_RCTRL)
        .value("S_RSHIFT", SDL_SCANCODE_RSHIFT)
        .value("S_RALT", SDL_SCANCODE_RALT)
        .value("S_RGUI", SDL_SCANCODE_RGUI)

        .value("S_MODE", SDL_SCANCODE_MODE)
        .value("S_SLEEP", SDL_SCANCODE_SLEEP)
        .value("S_WAKE", SDL_SCANCODE_WAKE)
        .value("S_CHANNEL_INC", SDL_SCANCODE_CHANNEL_INCREMENT)
        .value("S_CHANNEL_DEC", SDL_SCANCODE_CHANNEL_DECREMENT)
        .value("S_MEDIA_PLAY", SDL_SCANCODE_MEDIA_PLAY)
        .value("S_MEDIA_PAUSE", SDL_SCANCODE_MEDIA_PAUSE)
        .value("S_MEDIA_REC", SDL_SCANCODE_MEDIA_RECORD)
        .value("S_MEDIA_FAST_FORWARD", SDL_SCANCODE_MEDIA_FAST_FORWARD)
        .value("S_MEDIA_REWIND", SDL_SCANCODE_MEDIA_REWIND)
        .value("S_MEDIA_NEXT", SDL_SCANCODE_MEDIA_NEXT_TRACK)
        .value("S_MEDIA_PREV", SDL_SCANCODE_MEDIA_PREVIOUS_TRACK)
        .value("S_MEDIA_STOP", SDL_SCANCODE_MEDIA_STOP)
        .value("S_MEDIA_EJECT", SDL_SCANCODE_MEDIA_EJECT)
        .value("S_MEDIA_PLAY_PAUSE", SDL_SCANCODE_MEDIA_PLAY_PAUSE)
        .value("S_MEDIA_SELECT", SDL_SCANCODE_MEDIA_SELECT)

        .value("S_SOFTLEFT", SDL_SCANCODE_SOFTLEFT)
        .value("S_SOFTRIGHT", SDL_SCANCODE_SOFTRIGHT)
        .value("S_CALL", SDL_SCANCODE_CALL)
        .value("S_ENDCALL", SDL_SCANCODE_ENDCALL)

        .export_values()
        .finalize();

    // Keycodes
    py::native_enum<Keycode>(module, "Keycode", "enum.IntEnum")
        .value("K_UNKNOWN", Keycode::K_UNKNOWN)
        .value("K_RETURN", Keycode::K_RETURN)
        .value("K_ESC", Keycode::K_ESC)
        .value("K_BACKSPACE", Keycode::K_BACKSPACE)
        .value("K_TAB", Keycode::K_TAB)
        .value("K_SPACE", Keycode::K_SPACE)
        .value("K_EXCLAIM", Keycode::K_EXCLAIM)
        .value("K_DBLQUOTE", Keycode::K_DBLQUOTE)
        .value("K_HASH", Keycode::K_HASH)
        .value("K_DOLLAR", Keycode::K_DOLLAR)
        .value("K_PERCENT", Keycode::K_PERCENT)
        .value("K_AMPERSAND", Keycode::K_AMPERSAND)
        .value("K_SGLQUOTE", Keycode::K_SGLQUOTE)
        .value("K_LPAREN", Keycode::K_LPAREN)
        .value("K_RPAREN", Keycode::K_RPAREN)
        .value("K_ASTERISK", Keycode::K_ASTERISK)
        .value("K_PLUS", Keycode::K_PLUS)
        .value("K_COMMA", Keycode::K_COMMA)
        .value("K_MINUS", Keycode::K_MINUS)
        .value("K_PERIOD", Keycode::K_PERIOD)
        .value("K_SLASH", Keycode::K_SLASH)
        .value("K_0", Keycode::K_0)
        .value("K_1", Keycode::K_1)
        .value("K_2", Keycode::K_2)
        .value("K_3", Keycode::K_3)
        .value("K_4", Keycode::K_4)
        .value("K_5", Keycode::K_5)
        .value("K_6", Keycode::K_6)
        .value("K_7", Keycode::K_7)
        .value("K_8", Keycode::K_8)
        .value("K_9", Keycode::K_9)
        .value("K_COLON", Keycode::K_COLON)
        .value("K_SEMICOLON", Keycode::K_SEMICOLON)
        .value("K_LT", Keycode::K_LT)
        .value("K_EQ", Keycode::K_EQ)
        .value("K_GT", Keycode::K_GT)
        .value("K_QUESTION", Keycode::K_QUESTION)
        .value("K_AT", Keycode::K_AT)
        .value("K_LBRACKET", Keycode::K_LBRACKET)
        .value("K_BACKSLASH", Keycode::K_BACKSLASH)
        .value("K_RBRACKET", Keycode::K_RBRACKET)
        .value("K_CARET", Keycode::K_CARET)
        .value("K_UNDERSCORE", Keycode::K_UNDERSCORE)
        .value("K_GRAVE", Keycode::K_GRAVE)
        .value("K_a", Keycode::K_a)
        .value("K_b", Keycode::K_b)
        .value("K_c", Keycode::K_c)
        .value("K_d", Keycode::K_d)
        .value("K_e", Keycode::K_e)
        .value("K_f", Keycode::K_f)
        .value("K_g", Keycode::K_g)
        .value("K_h", Keycode::K_h)
        .value("K_i", Keycode::K_i)
        .value("K_j", Keycode::K_j)
        .value("K_k", Keycode::K_k)
        .value("K_l", Keycode::K_l)
        .value("K_m", Keycode::K_m)
        .value("K_n", Keycode::K_n)
        .value("K_o", Keycode::K_o)
        .value("K_p", Keycode::K_p)
        .value("K_q", Keycode::K_q)
        .value("K_r", Keycode::K_r)
        .value("K_s", Keycode::K_s)
        .value("K_t", Keycode::K_t)
        .value("K_u", Keycode::K_u)
        .value("K_v", Keycode::K_v)
        .value("K_w", Keycode::K_w)
        .value("K_x", Keycode::K_x)
        .value("K_y", Keycode::K_y)
        .value("K_z", Keycode::K_z)
        .value("K_LBRACE", Keycode::K_LBRACE)
        .value("K_PIPE", Keycode::K_PIPE)
        .value("K_RBRACE", Keycode::K_RBRACE)
        .value("K_TILDE", Keycode::K_TILDE)
        .value("K_DEL", Keycode::K_DEL)
        .value("K_CAPS", Keycode::K_CAPS)
        .value("K_F1", Keycode::K_F1)
        .value("K_F2", Keycode::K_F2)
        .value("K_F3", Keycode::K_F3)
        .value("K_F4", Keycode::K_F4)
        .value("K_F5", Keycode::K_F5)
        .value("K_F6", Keycode::K_F6)
        .value("K_F7", Keycode::K_F7)
        .value("K_F8", Keycode::K_F8)
        .value("K_F9", Keycode::K_F9)
        .value("K_F10", Keycode::K_F10)
        .value("K_F11", Keycode::K_F11)
        .value("K_F12", Keycode::K_F12)
        .value("K_PRTSCR", Keycode::K_PRTSCR)
        .value("K_SCRLK", Keycode::K_SCRLK)
        .value("K_PAUSE", Keycode::K_PAUSE)
        .value("K_INS", Keycode::K_INS)
        .value("K_HOME", Keycode::K_HOME)
        .value("K_PGUP", Keycode::K_PGUP)
        .value("K_END", Keycode::K_END)
        .value("K_PGDOWN", Keycode::K_PGDOWN)
        .value("K_RIGHT", Keycode::K_RIGHT)
        .value("K_LEFT", Keycode::K_LEFT)
        .value("K_DOWN", Keycode::K_DOWN)
        .value("K_UP", Keycode::K_UP)
        .value("K_NUMLOCK", Keycode::K_NUMLOCK)
        .value("K_KP_DIV", Keycode::K_KP_DIV)
        .value("K_KP_MULT", Keycode::K_KP_MULT)
        .value("K_KP_MINUS", Keycode::K_KP_MINUS)
        .value("K_KP_PLUS", Keycode::K_KP_PLUS)
        .value("K_KP_ENTER", Keycode::K_KP_ENTER)
        .value("K_KP_1", Keycode::K_KP_1)
        .value("K_KP_2", Keycode::K_KP_2)
        .value("K_KP_3", Keycode::K_KP_3)
        .value("K_KP_4", Keycode::K_KP_4)
        .value("K_KP_5", Keycode::K_KP_5)
        .value("K_KP_6", Keycode::K_KP_6)
        .value("K_KP_7", Keycode::K_KP_7)
        .value("K_KP_8", Keycode::K_KP_8)
        .value("K_KP_9", Keycode::K_KP_9)
        .value("K_KP_0", Keycode::K_KP_0)
        .value("K_KP_PERIOD", Keycode::K_KP_PERIOD)
        .value("K_APPLICATION", Keycode::K_APPLICATION)
        .value("K_POWER", Keycode::K_POWER)
        .value("K_F13", Keycode::K_F13)
        .value("K_F14", Keycode::K_F14)
        .value("K_F15", Keycode::K_F15)
        .value("K_EXECUTE", Keycode::K_EXECUTE)
        .value("K_HELP", Keycode::K_HELP)
        .value("K_MENU", Keycode::K_MENU)
        .value("K_SELECT", Keycode::K_SELECT)
        .value("K_STOP", Keycode::K_STOP)
        .value("K_AGAIN", Keycode::K_AGAIN)
        .value("K_UNDO", Keycode::K_UNDO)
        .value("K_CUT", Keycode::K_CUT)
        .value("K_COPY", Keycode::K_COPY)
        .value("K_PASTE", Keycode::K_PASTE)
        .value("K_FIND", Keycode::K_FIND)
        .value("K_MUTE", Keycode::K_MUTE)
        .value("K_VOLUP", Keycode::K_VOLUP)
        .value("K_VOLDOWN", Keycode::K_VOLDOWN)
        .value("K_LCTRL", Keycode::K_LCTRL)
        .value("K_LSHIFT", Keycode::K_LSHIFT)
        .value("K_LALT", Keycode::K_LALT)
        .value("K_LGUI", Keycode::K_LGUI)
        .value("K_RCTRL", Keycode::K_RCTRL)
        .value("K_RSHIFT", Keycode::K_RSHIFT)
        .value("K_RALT", Keycode::K_RALT)
        .value("K_RGUI", Keycode::K_RGUI)
        .value("K_MODE", Keycode::K_MODE)
        .value("K_SLEEP", Keycode::K_SLEEP)
        .value("K_WAKE", Keycode::K_WAKE)
        .value("K_CHANNEL_INC", Keycode::K_CHANNEL_INC)
        .value("K_CHANNEL_DEC", Keycode::K_CHANNEL_DEC)
        .value("K_MEDIA_PLAY", Keycode::K_MEDIA_PLAY)
        .value("K_MEDIA_PAUSE", Keycode::K_MEDIA_PAUSE)
        .value("K_MEDIA_REC", Keycode::K_MEDIA_REC)
        .value("K_MEDIA_FF", Keycode::K_MEDIA_FF)
        .value("K_MEDIA_REWIND", Keycode::K_MEDIA_REWIND)
        .value("K_MEDIA_NEXT", Keycode::K_MEDIA_NEXT)
        .value("K_MEDIA_PREV", Keycode::K_MEDIA_PREV)
        .value("K_MEDIA_STOP", Keycode::K_MEDIA_STOP)
        .value("K_MEDIA_EJECT", Keycode::K_MEDIA_EJECT)
        .value("K_MEDIA_PLAY_PAUSE", Keycode::K_MEDIA_PLAY_PAUSE)
        .value("K_MEDIA_SELECT", Keycode::K_MEDIA_SELECT)
        .value("K_SOFTLEFT", Keycode::K_SOFTLEFT)
        .value("K_SOFTRIGHT", Keycode::K_SOFTRIGHT)
        .value("K_CALL", Keycode::K_CALL)
        .value("K_ENDCALL", Keycode::K_ENDCALL)
        .export_values()
        .finalize();

    // Gamepad buttons
    py::native_enum<SDL_GamepadButton>(module, "GamepadButton", "enum.IntEnum")
        .value("C_SOUTH", SDL_GAMEPAD_BUTTON_SOUTH)
        .value("C_EAST", SDL_GAMEPAD_BUTTON_EAST)
        .value("C_WEST", SDL_GAMEPAD_BUTTON_WEST)
        .value("C_NORTH", SDL_GAMEPAD_BUTTON_NORTH)
        .value("C_BACK", SDL_GAMEPAD_BUTTON_BACK)
        .value("C_GUIDE", SDL_GAMEPAD_BUTTON_GUIDE)
        .value("C_START", SDL_GAMEPAD_BUTTON_START)
        .value("C_LSTICK", SDL_GAMEPAD_BUTTON_LEFT_STICK)
        .value("C_RSTICK", SDL_GAMEPAD_BUTTON_RIGHT_STICK)
        .value("C_LSHOULDER", SDL_GAMEPAD_BUTTON_LEFT_SHOULDER)
        .value("C_RSHOULDER", SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER)
        .value("C_DPAD_UP", SDL_GAMEPAD_BUTTON_DPAD_UP)
        .value("C_DPAD_DOWN", SDL_GAMEPAD_BUTTON_DPAD_DOWN)
        .value("C_DPAD_LEFT", SDL_GAMEPAD_BUTTON_DPAD_LEFT)
        .value("C_DPAD_RIGHT", SDL_GAMEPAD_BUTTON_DPAD_RIGHT)
        .export_values()
        .finalize();

    // Gamepad axes
    py::native_enum<SDL_GamepadAxis>(module, "GamepadAxis", "enum.IntEnum")
        .value("C_LX", SDL_GAMEPAD_AXIS_LEFTX)
        .value("C_LY", SDL_GAMEPAD_AXIS_LEFTY)
        .value("C_RX", SDL_GAMEPAD_AXIS_RIGHTX)
        .value("C_RY", SDL_GAMEPAD_AXIS_RIGHTY)
        .value("C_LTRIGGER", SDL_GAMEPAD_AXIS_LEFT_TRIGGER)
        .value("C_RTRIGGER", SDL_GAMEPAD_AXIS_RIGHT_TRIGGER)
        .export_values()
        .finalize();

    // Gamepad types
    py::native_enum<SDL_GamepadType>(module, "GamepadType", "enum.IntEnum")
        .value("C_STANDARD", SDL_GAMEPAD_TYPE_STANDARD)
        .value("C_XBOX_360", SDL_GAMEPAD_TYPE_XBOX360)
        .value("C_XBOX_ONE", SDL_GAMEPAD_TYPE_XBOXONE)
        .value("C_PS3", SDL_GAMEPAD_TYPE_PS3)
        .value("C_PS4", SDL_GAMEPAD_TYPE_PS4)
        .value("C_PS5", SDL_GAMEPAD_TYPE_PS5)
        .value("C_SWITCH_PRO", SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO)
        .value("C_SWITCH_JOYCON_LEFT", SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT)
        .value("C_SWITCH_JOYCON_RIGHT", SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT)
        .value("C_SWITCH_JOYCON_PAIR", SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR)
        .export_values()
        .finalize();
}
}  // namespace kn::constants
