name: Windows

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_call: # So other workflows can call this

  workflow_dispatch: # So I can manually trigger it on GitHub

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-windows
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.winarch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { winarch: AMD64, msvc-dev-arch: x86_amd64 }
          - { winarch: x86, msvc-dev-arch: x86 }

    env:
      CIBW_ARCHS: ${{ matrix.winarch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build-core cibuildwheel
        timeout-minutes: 5

      - name: Set up vcpkg and install SDL3 deps
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "latest"
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"
          runVcpkgInstall: true
          vcpkgJsonGlob: "**/vcpkg.json"

      - name: Copy SDL runtime DLLs into package
        run: |
          $archPath = if ('${{ matrix.winarch }}' -eq 'x86') { 'x86-windows' } else { 'x64-windows' }
          Copy-Item "vcpkg\installed\$archPath\bin\SDL3*.dll" -Destination "src\pykraken\" -Force
        shell: powershell

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --platform windows
        env:
          CIBW_SKIP: "pp*"
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels-${{ matrix.winarch }}
          path: wheelhouse/*.whl
